import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'zh' | 'tl';

const translations = {
  en: {
    quick_log: "Quick Log",
    timeline: "Timeline",
    no_recent_activity: "No recent activity.",
    blood_glucose: "Blood Glucose",
    take_photo: "Take Photo",
    submit: "Submit",
    confirm: "Confirm",
    sign_in: "Sign In",
    logout: "Log Out",
    dashboard: "Dashboard",
    generate_note: "Generate Note",
    speak: "Speak (Any Language)",
    listening: "Listening...",
    ai_disclaimer: "⚠️ AI is for assistance only. Final clinical judgement must be made by a Registered Nurse.",
    offline: "⚠️ Offline Mode: Data temporarily saved to local cache.",
    roster: "Roster",
    staff: "Staff",
    handover: "Handover",
    live_dashboard: "Live Dashboard",
    real_time_overview: "Real-time resident wellness overview",
    find_resident: "Find resident...",
    log_sirs_incident: "Log SIRS Incident",
    room: "Room",
    care_minutes: "Care Minutes",
    status: "Status",
    basic_care_tasks: "Basic Care Tasks",
    bath: "Bath",
    meal: "Meal",
    toilet: "Toilet",
    app_title: "Sunrise Care System",
    app_title_short: "Sunrise",
    exec_view: "Exec View",
    sirs_hub: "SIRS Hub",
    shift_handover_report: "Shift Handover Report",
    synthesizing_clinical_handover: "Synthesizing clinical handover data...",
    simulator: "Simulator",
    trigger_iot_fall_alert: "🚨 Trigger IoT Fall Alert",
    toggle_rn_coverage_alert: "⚠️ Toggle RN Coverage Alert",
    critical_alert_rn_coverage: "CRITICAL ALERT: No Registered Nurse currently signed into the shift. Care teams must operate under mandatory escalation protocols.",
    appreciation_received: "Appreciation Received!",
    sent_appreciation_for_care: "sent appreciation for your care today.",
    sirs_priority_alert: "SIRS Priority Alert",
    view_resident_profile_ai_triage: "View Resident Profile & AI Triage",
    my_submitted_observations: "My Submitted Observations",
    track_observation_status: "Track the status of your reported notes and photos",
    no_pending_observations: "You have no pending observations waiting for RN review.",
    waiting_rn_review: "Waiting RN Review",
    room_prefix: "Room",
    loading_dashboard: "Loading Dashboard Data...",
    sign_out: "Sign Out",
    done: "Done",
    due: "Due",
    overdue: "Overdue",
    eaten: "Eaten",
    assisted: "Assisted",
    "pad-change": "Pad Changed",
    missed: "Missed",
    independent: "Independent",
    dependent: "Dependent",
    back_to_dashboard: "Back to Dashboard",
    mins: "mins",
    medical_profile: "Medical Profile",
    past_medical_history: "Past Medical History",
    current_medications: "Current Medications",
    allergies: "Allergies",
    none_recorded: "None recorded",
    no_recorded_allergies: "No recorded allergies",
    todays_summary: "Today's Summary",
    generate_todays_summary: "Generate Today's Summary",
    generate: "Generate",
    gemini_is_summarising: "Gemini is summarising today's records...",
    daily_wellness_summary: "Daily Wellness Summary",
    family_update_desensitized: "Family Update (Desensitized)",
    privacy_preserving_mode_active: "Privacy-Preserving Mode Active (Privacy Act 1988 / APPs)",
    generate_family_update: "Generate Family Update",
    gemini_drafting_family_update: "Gemini is drafting a family-friendly update...",
    draft_message: "Draft Message",
    needs_rn_approval: "Needs RN Approval",
    approved_sent_to_family: "Approved & Sent to Family",
    rn_approve_send_to_family: "RN Approve & Send to Family Portal",
    generate_desensitized_summary_desc: "Generate a desensitized summary of the resident's status today to share with their family members.",
    record_observation: "Record Observation",
    select_location_first: "Select a location first, then add a photo (or proceed without location).",
    now_take_photo: "Now take a photo, or drag and drop a picture for AI-assisted documentation.",
    take_photo_btn: "Take Photo",
    upload_file: "Upload File",
    gemini_analyzing: "Gemini is analyzing... (results usually appear within {s} seconds)",
    processing_observation_securely: "Processing the observation securely.",
    analysis_failed: "Analysis Failed",
    ai_observation_note: "AI Observation Note",
    draft: "Draft",
    critical_symptom_detected: "CRITICAL SYMPTOM DETECTED",
    critical_symptom_detected_desc: "Bypassing standard AI workflow. Immediate RN Review or Code Blue required depending on severity.",
    colour: "Colour",
    bristol_stool_type: "Bristol Stool Type",
    visual_observation: "Visual Observation",
    potential_risk_flag: "Potential Risk Flag",
    size_type_estimate: "Size / Type Estimate",
    location: "Location",
    suggested_care_plan: "Suggested Temporary Care Plan (Pending RN)",
    submitted_for_rn_review: "Submitted for RN Review",
    submit_for_rn_review: "Submit for RN Review",
    rn_review_queue: "RN Review Pending Queue",
    no_pending_reviews: "No pending observations require RN review.",
    add_note_override: "Add Annotation / Override",
    confirm_save_record: "Confirm & Save to Record",
    ai_observation_disclaimer: "AI observation, not a medical diagnosis. RN confirmation required.",
    requires_rn_signature: "Needs RN Sign-off",
    sirs_incident_report_badge: "SIRS Incident Report",
    ai_suggested_care_plan: "AI Suggested Care Plan (Aged Care Guidelines)",
    native_confirmation_retranslation: "Native Confirmation Retranslation",
    caregiver_voice_intake: "Caregiver Voice Intake",
    transcribed_and_compiled: "Transcribed and clinical note compiled by AI",
    no_image_available: "No Image Available",
    no_active_ai_observation: "No active AI observation",
    upload_photo_instruction: "Upload a photo to see the automated clinical note draft here.",
    daily_care_note_generator: "Daily Care Note Generator",
    live_voice_clinical_notes: "Live Voice Clinical Notes",
    listening_in_any_language: "Listening in any language...",
    tap_to_dictate_observation: "Tap to Dictate Observation",
    voice_not_supported: "Browser Voice Recording Not Supported",
    recording_speak_instruction: "Recording... Speak your observation (e.g., in Chinese about a fall)",
    or_type_manually: "Or type manually:",
    placeholder_care_note_example: "E.g. Resident had a fall in the bathroom and hit their head...",
    generate_clinical_note: "Generate Clinical Note (Text Input)",
    processing_clinical_ai: "Processing with Clinical AI...",
    transcribing_and_translating: "Transcribing & translating audio...",
    generating_clinical_note: "Generating clinical note...",
    checking_sirs_compliance: "Checking SIRS compliance rules...",
    gemini_drafting_note: "Gemini is drafting the note...",
    processing_failed: "Processing Failed",
    retry_audio_analysis: "Retry Audio Analysis",
    dismiss: "Dismiss",
    generated_progress_note: "Generated Progress Note",
    native_translation_confirmation: "Native Translation Confirmation",
    read_back: "Read back",
    suggested_follow_ups: "Suggested Follow-ups (Not yet documented)",
    sirs_detected: "SIRS Priority Detected",
    sirs_detected_desc: "The AI detected a potential reportable incident. You must log this to the Serious Incident Response Scheme.",
    review_submit_sirs: "Review & Submit SIRS Report",
    saved_to_resident_record: "Saved to Resident Record",
    save_to_resident_record: "Save to Resident Record",
    clinical_note_will_appear: "The clinical progress note will appear here.",
    mins_suffix: "m",
    error: "Error",
    roster_compliance_guard: "Roster Compliance Guard",
    save_roster: "Save Roster",
    care_minutes_target: "Care Minutes Target",
    average_total_care_minutes: "Average Total Care Minutes",
    of_which_rn_minutes: "Of which RN Minutes",
    rn_coverage_status: "24/7 RN Coverage Status",
    weekly_roster_view: "Weekly Roster View",
    roster_breach_alert: "Aged Care Act breach: No Registered Nurse coverage",
    shifts_covered: "shifts covered",
    required_rn_onsite: "The Aged Care Act requires at least one Registered Nurse on-site and on duty at all times.",
    risk_sanction_msg: "This facility is at risk of regulatory sanction. The roster cannot be saved until coverage is secured.",
    missing_rn_for: "Missing RN for",
    shift_word: "shift"
  },
  zh: {
    quick_log: "快速记录",
    timeline: "时间线",
    no_recent_activity: "无近期活动。",
    blood_glucose: "血糖",
    take_photo: "拍照",
    submit: "提交",
    confirm: "确认",
    sign_in: "登录",
    logout: "登出",
    dashboard: "仪表板",
    generate_note: "生成记录",
    speak: "语音输入 (自动翻译)",
    listening: "聆听中...",
    ai_disclaimer: "⚠️ AI仅辅助，最终医疗判断以RN(注册护士)为准。",
    offline: "⚠️ 离线模式：数据已暂存本地，联网后同步。",
    roster: "排班",
    staff: "员工管理",
    handover: "交接班",
    live_dashboard: "实时看板",
    real_time_overview: "实时居民健康概览",
    find_resident: "搜索长者...",
    log_sirs_incident: "上报 SIRS 事件",
    room: "房间号",
    care_minutes: "护理时长",
    status: "状态",
    basic_care_tasks: "基础护理",
    bath: "洗浴",
    meal: "进餐",
    toilet: "如厕",
    app_title: "晨曦关怀系统",
    app_title_short: "晨曦",
    exec_view: "管理看板",
    sirs_hub: "SIRS 中心",
    shift_handover_report: "班次交接报告",
    synthesizing_clinical_handover: "正在综合临床交接数据...",
    simulator: "模拟器工具",
    trigger_iot_fall_alert: "🚨 触发 IoT 跌倒警报",
    toggle_rn_coverage_alert: "⚠️ 切换 RN 覆盖警报",
    critical_alert_rn_coverage: "关键警报：当前班次无注册护士登录。护理团队必须启动强制升级流程。",
    appreciation_received: "收到家属感谢！",
    sent_appreciation_for_care: "对您今天的护理工作表示感谢。",
    sirs_priority_alert: "SIRS 紧急警报",
    view_resident_profile_ai_triage: "查看居民档案与 AI 分诊",
    my_submitted_observations: "我提交的观察记录",
    track_observation_status: "跟踪您上报的记录和照片的状态",
    no_pending_observations: "您目前没有等待注册护士 (RN) 审核的观察记录。",
    waiting_rn_review: "等待护士审核",
    room_prefix: "房号",
    loading_dashboard: "正在加载看板数据...",
    sign_out: "登出",
    done: "已完成",
    due: "待办",
    overdue: "逾期",
    eaten: "已进食",
    assisted: "协助",
    missed: "未进食",
    independent: "自主",
    dependent: "依赖",
    back_to_dashboard: "返回看板",
    mins: "分钟",
    medical_profile: "医疗档案",
    past_medical_history: "既往病史",
    current_medications: "当前用药",
    allergies: "过敏史",
    none_recorded: "无记录",
    no_recorded_allergies: "无过敏史记录",
    todays_summary: "今日摘要",
    generate_todays_summary: "生成今日摘要",
    generate: "生成",
    gemini_is_summarising: "Gemini 正在汇总今天的记录...",
    daily_wellness_summary: "每日健康摘要",
    family_update_desensitized: "家属更新 (已脱敏保护隐私)",
    privacy_preserving_mode_active: "隐私保护模式已激活 (澳大利亚1988隐私法)",
    generate_family_update: "生成家属更新",
    gemini_drafting_family_update: "Gemini 正在撰写适合家属阅读的更新内容...",
    draft_message: "草稿信息",
    needs_rn_approval: "需注册护士 (RN) 审核",
    approved_sent_to_family: "已批准并发送给家属",
    rn_approve_send_to_family: "护士批准并发送至家属门户",
    generate_desensitized_summary_desc: "生成该长者今日状态的脱敏摘要，以便与家属成员分享。",
    record_observation: "记录临床观察",
    select_location_first: "请先选择身体部位，然后添加照片 (或不选部位直接继续)。",
    now_take_photo: "现在拍摄照片，或拖放图片以进行 AI 辅助文档化。",
    take_photo_btn: "拍照拍摄",
    upload_file: "上传图片",
    gemini_analyzing: "Gemini 正在分析中... (结果通常在{s}秒内显示)",
    processing_observation_securely: "正在安全处理该临床观察数据。",
    analysis_failed: "分析失败",
    ai_observation_note: "AI 临床观察记录",
    draft: "草稿",
    critical_symptom_detected: "检测到关键危急症状",
    critical_symptom_detected_desc: "绕过标准 AI 流程。根据严重程度，需要立即由注册护士 (RN) 审核或启动紧急救治 (Code Blue)。",
    visual_observation: "视觉观察记录",
    colour: "颜色",
    bristol_stool_type: "布里斯托大便分类",
    potential_risk_flag: "潜在风险标识",
    size_type_estimate: "尺寸 / 类型评估",
    location: "身体部位",
    suggested_care_plan: "建议的临时护理方案 (待注册护士审核)",
    submitted_for_rn_review: "已提交等待护士审核",
    submit_for_rn_review: "提交护士审核",
    rn_review_queue: "护士待审核队列",
    no_pending_reviews: "没有需要护士审核的观察记录。",
    add_note_override: "添加注释/覆盖",
    confirm_save_record: "确认并保存到记录",
    ai_observation_disclaimer: "人工智能观察结果，并非医学诊断。需注册护士确认。",
    requires_rn_signature: "需要注册护士签字",
    sirs_incident_report_badge: "SIRS 事件报告",
    ai_suggested_care_plan: "人工智能建议的护理计划 (老年护理指南)",
    native_confirmation_retranslation: "母语确认与重译",
    caregiver_voice_intake: "护理人员语音输入",
    transcribed_and_compiled: "AI 转录并生成的临床记录",
    no_image_available: "无图片",
    no_active_ai_observation: "无进行中的 AI 临床观察",
    upload_photo_instruction: "上传照片后，此处将自动显示临床记录草稿。",
    daily_care_note_generator: "每日护理记录生成器",
    live_voice_clinical_notes: "实时语音临床记录",
    listening_in_any_language: "正在聆听中 (支持任意语言)...",
    tap_to_dictate_observation: "点击开始语音记录",
    voice_not_supported: "浏览器不支持语音录音",
    recording_speak_instruction: "正在录音... 请说出您的观察结果 (例如使用中文描述跌倒过程)",
    or_type_manually: "或手动输入:",
    placeholder_care_note_example: "例如：长者在浴室不慎跌倒并撞到了头部...",
    generate_clinical_note: "生成临床记录 (通过文字输入)",
    processing_clinical_ai: "正在通过临床 AI 处理...",
    transcribing_and_translating: "正在转录并翻译语音...",
    generating_clinical_note: "正在生成临床记录...",
    checking_sirs_compliance: "正在检查 SIRS 合规规则...",
    gemini_drafting_note: "Gemini 正在起草记录...",
    processing_failed: "处理失败",
    retry_audio_analysis: "重试语音分析",
    dismiss: "忽略",
    generated_progress_note: "生成的病程进展记录",
    native_translation_confirmation: "原始语言翻译确认",
    read_back: "语音朗读",
    suggested_follow_ups: "建议的后续跟进 (尚未记录)",
    sirs_detected: "检测到 SIRS 紧急事件",
    sirs_detected_desc: "AI 检测到潜在的应报告事件。您必须将其上报至严重事件响应计划 (SIRS)。",
    review_submit_sirs: "审核并提交 SIRS 报告",
    saved_to_resident_record: "已保存至长者档案",
    save_to_resident_record: "保存至长者档案",
    clinical_note_will_appear: "生成的临床病程进展记录将在此处显示。",
    mins_suffix: "分钟",
    error: "错误",
    roster_compliance_guard: "排班合规守护引擎",
    save_roster: "保存排班计划",
    care_minutes_target: "每日护理时长指标",
    average_total_care_minutes: "平均总护理时间",
    of_which_rn_minutes: "其中注册护士 (RN) 时间",
    rn_coverage_status: "24/7 注册护士 (RN) 覆盖状态",
    weekly_roster_view: "周排班表视图",
    roster_breach_alert: "违反《老年人护理法》：无注册护士覆盖",
    shifts_covered: "班次已覆盖",
    required_rn_onsite: "《老年人护理法》规定任何时候都必须有至少一名注册护士在岗值班。",
    risk_sanction_msg: "该机构存在严重的合规制裁风险。在确保护士覆盖前，排班计划无法保存锁定。",
    missing_rn_for: "缺少注册护士：",
    shift_word: "班次"
  },
  tl: {
    quick_log: "Mabilis na Tala",
    timeline: "Timeline",
    no_recent_activity: "Walang kamakailang aktibidad.",
    blood_glucose: "Blood Glucose",
    take_photo: "Kumuha ng Litrato",
    submit: "Isumite",
    confirm: "Kumpirmahin",
    sign_in: "Mag-sign In",
    logout: "Mag-log Out",
    dashboard: "Dashboard",
    generate_note: "Bumuo ng Tala",
    speak: "Magsalita (Kahit Anong Wika)",
    listening: "Nakikinig...",
    ai_disclaimer: "⚠️ Ang AI ay para sa tulong lamang. Ang RN ang magdedesisyon.",
    offline: "⚠️ Offline Mode: Pansamantalang nai-save ang data.",
    roster: "Roster",
    staff: "Kawani",
    handover: "Handover",
    live_dashboard: "Live Dashboard",
    real_time_overview: "Real-time na pangkalahatang ideya",
    find_resident: "Maghanap ng residente...",
    log_sirs_incident: "I-log ang SIRS Incident",
    room: "Kwarto",
    care_minutes: "Care Minutes",
    status: "Katayuan",
    basic_care_tasks: "Pangunahing Pangangalaga",
    bath: "Paligo",
    meal: "Pagkain",
    toilet: "Banyo",
    app_title: "Sunrise Sistema ng Pangangalaga",
    app_title_short: "Sunrise",
    exec_view: "Pananaw ng Ehekutibo",
    sirs_hub: "Sentro ng SIRS",
    shift_handover_report: "Ulat sa Paglilipat ng Shift",
    synthesizing_clinical_handover: "Nagsasama-sama ng data ng paglilipat ng klinikal...",
    simulator: "Simulator",
    trigger_iot_fall_alert: "🚨 I-trigger ang IoT Alert sa Pagkahulog",
    toggle_rn_coverage_alert: "⚠️ I-toggle ang Alert sa Coverage ng RN",
    critical_alert_rn_coverage: "MATINDING ALERT: Walang Registered Nurse na kasalukuyang naka-sign in sa shift. Ang mga koponan ay dapat sumunod sa mandatoryong protocol.",
    appreciation_received: "Nakatanggap ng Pasasalamat!",
    sent_appreciation_for_care: "nagpadala ng pasasalamat para sa iyong pag-aalaga ngayon.",
    sirs_priority_alert: "Alert sa Priority ng SIRS",
    view_resident_profile_ai_triage: "Tingnan ang Profile ng Residente at AI Triage",
    my_submitted_observations: "Aking mga Naipadalang Obserbasyon",
    track_observation_status: "Subaybayan ang katayuan ng iyong mga iniulat na tala at larawan",
    no_pending_observations: "Wala kang mga nakabinbing obserbasyon na naghihintay para sa pagsusuri ng RN.",
    waiting_rn_review: "Naghihintay ng Pagsusuri ng RN",
    room_prefix: "Kwarto",
    loading_dashboard: "Naglo-load ng Data ng Dashboard...",
    sign_out: "Mag-sign Out",
    done: "Tapos na",
    due: "Nakatakda",
    overdue: "Huli na",
    eaten: "Kumain na",
    assisted: "Inalalayan",
    missed: "Nalaktawan",
    independent: "Malaya",
    dependent: "Dependiyente",
    back_to_dashboard: "Bumalik sa Dashboard",
    mins: "mins",
    medical_profile: "Profile ng Medikal",
    past_medical_history: "Nakaraang Kasaysayan ng Medikal",
    current_medications: "Kasalukuyang Gamot",
    allergies: "Mga Alerdyi",
    none_recorded: "Walang nakarekord",
    no_recorded_allergies: "Walang nakatalang alerdyi",
    todays_summary: "Buod Ngayon",
    generate_todays_summary: "Bumuo ng Buod Ngayon",
    generate: "Bumuo",
    gemini_is_summarising: "Inilalagom ng Gemini ang mga tala ngayong araw...",
    daily_wellness_summary: "Araw-araw na Buod ng Kalusugan",
    family_update_desensitized: "Update sa Pamilya (Desensitized)",
    privacy_preserving_mode_active: "Aktibo ang Mode ng Pagpapanatili ng Privacy (Privacy Act 1988 / APPs)",
    generate_family_update: "Bumuo ng Update sa Pamilya",
    gemini_drafting_family_update: "Gumagawa ang Gemini ng draft ng update para sa pamilya...",
    draft_message: "Draft na Mensahe",
    needs_rn_approval: "Kailangan ng Pag-apruba ng RN",
    approved_sent_to_family: "Inaprubahan at Ipinadala sa Pamilya",
    rn_approve_send_to_family: "Aprubahan ng RN at Ipadala sa Portal ng Pamilya",
    generate_desensitized_summary_desc: "Bumuo ng desensitized na buod ng katayuan ng residente ngayon upang maibahagi sa kanilang mga miyembro ng pamilya.",
    record_observation: "I-record ang Obserbasyon",
    select_location_first: "Pumili muna ng lokasyon, pagkatapos ay magdagdag ng larawan (o magpatuloy nang walang lokasyon).",
    now_take_photo: "Kumuha ng larawan ngayon, o i-drag at i-drop ang larawan para sa dokumentasyong tulong ng AI.",
    take_photo_btn: "Kumuha ng Larawan",
    upload_file: "Mag-upload ng File",
    gemini_analyzing: "Sinusuri ng Gemini... (karaniwang lumalabas ang mga resulta sa loob ng {s} segundo)",
    processing_observation_securely: "Ligtas na pinoproseso ang obserbasyon.",
    analysis_failed: "Bigo ang Pagsusuri",
    ai_observation_note: "Tala ng Obserbasyon ng AI",
    draft: "Draft",
    critical_symptom_detected: "NATUKLASANG MATINDING SYMPTOMA",
    critical_symptom_detected_desc: "Nilampasan ang karaniwang workflow ng AI. Kailangan ng agarang Pagsusuri ng RN o Code Blue depende sa tindi.",
    visual_observation: "Obserbasyon sa Visual",
    colour: "Kulay",
    bristol_stool_type: "Uri ng Bristol Stool",
    potential_risk_flag: "Posibleng Risk Flag",
    size_type_estimate: "Tantya sa Laki / Uri",
    location: "Lokasyon",
    suggested_care_plan: "Iminungkahing Pansamantalang Plano ng Pangangalaga (Naghihintay ng RN)",
    submitted_for_rn_review: "Naipadala na para sa Pagsusuri ng RN",
    submit_for_rn_review: "Isumite para sa Pagsusuri ng RN",
    rn_review_queue: "Pila ng Naghihintay ng Pagsusuri ng RN",
    no_pending_reviews: "Walang nakabinbing obserbasyon na kailangan suriin ng RN.",
    add_note_override: "Magdagdag ng Tala / I-override",
    confirm_save_record: "Kumpirmahin at I-save",
    ai_observation_disclaimer: "Obserbasyon ng AI, hindi medikal na diagnosis. Kailangan ng kumpirmasyon ng RN.",
    requires_rn_signature: "Kailangan ng Lagda ng RN",
    sirs_incident_report_badge: "Ulat ng Insidente sa SIRS",
    ai_suggested_care_plan: "Iminungkahing Plano ng Pangangalaga ng AI",
    native_confirmation_retranslation: "Katutubong Kumpirmasyon at Muling Pagsasalin",
    caregiver_voice_intake: "Input ng Boses ng Tagapag-alaga",
    transcribed_and_compiled: "Tinranscribe at binuo ng AI",
    no_image_available: "Walang Magagamit na Larawan",
    no_active_ai_observation: "Walang aktibong obserbasyon ng AI",
    upload_photo_instruction: "Mag-upload ng larawan para makita ang automated clinical note draft dito.",
    daily_care_note_generator: "Tagabuo ng Araw-araw na Tala ng Pangangalaga",
    live_voice_clinical_notes: "Live na Voice Clinical Notes",
    listening_in_any_language: "Nakikinig sa kahit anong wika...",
    tap_to_dictate_observation: "I-tap para Magdikta ng Obserbasyon",
    voice_not_supported: "Hindi Suportado ang Voice Recording sa Browser",
    recording_speak_instruction: "Nagre-record... Magsalita ng iyong obserbasyon (halimbawa, sa Tagalog o Chinese tungkol sa pagkahulog)",
    or_type_manually: "O i-type nang manu-mano:",
    placeholder_care_note_example: "Halimbawa: Ang residente ay nadulas sa banyo at nauntog ang ulo...",
    generate_clinical_note: "Bumuo ng Clinical Note (Text Input)",
    processing_clinical_ai: "Pinoproseso gamit ang Clinical AI...",
    transcribing_and_translating: "Kasalukuyang tina-transcribe at isinasalin ang audio...",
    generating_clinical_note: "Bumubuo ng clinical note...",
    checking_sirs_compliance: "Sinusuri ang mga panuntunan sa pagsunod sa SIRS...",
    gemini_drafting_note: "Gumagawa ang Gemini ng draft ng tala...",
    processing_failed: "Bigo ang Pagproseso",
    retry_audio_analysis: "Ulitin ang Pagsusuri ng Audio",
    dismiss: "I-dismiss",
    generated_progress_note: "Binuong Progress Note",
    native_translation_confirmation: "Kumpirmasyon ng Katutubong Pagsasalin",
    read_back: "Basahin pabalik",
    suggested_follow_ups: "Iminungkahing Follow-up (Hindi pa nakadokumento)",
    sirs_detected: "Natukoy ang Priority ng SIRS",
    sirs_detected_desc: "Natukoy ng AI ang isang posibleng reportable incident. Dapat mo itong i-log sa Serious Incident Response Scheme.",
    review_submit_sirs: "Suriin at Isumite ang SIRS Report",
    saved_to_resident_record: "Naka-save sa Record ng Residente",
    save_to_resident_record: "I-save sa Record ng Residente",
    clinical_note_will_appear: "Lilitaw ang clinical progress note dito.",
    mins_suffix: "m",
    error: "Error",
    roster_compliance_guard: "Roster Compliance Guard",
    save_roster: "I-save ang Roster",
    care_minutes_target: "Target ng Care Minutes",
    average_total_care_minutes: "Average na Total Care Minutes",
    of_which_rn_minutes: "Saka RN Minutes",
    rn_coverage_status: "24/7 Katayuan ng Coverage ng RN",
    weekly_roster_view: "Lingguhang Roster",
    roster_breach_alert: "Lumalabag sa Aged Care Act: Walang coverage ng RN",
    shifts_covered: "shifts covered",
    required_rn_onsite: "Ang Aged Care Act ay nangangailangan ng hindi bababa sa isang Registered Nurse on-site sa lahat ng oras.",
    risk_sanction_msg: "Ang pasilidad na ito ay nasa panganib ng regulatory sanction. Hindi mai-save ang roster.",
    missing_rn_for: "Kulang sa RN para sa",
    shift_word: "shift"
  }
};

const LanguageContext = createContext<{
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: keyof typeof translations.en) => string;
  isOnline: boolean;
  toggleSimulateOffline: () => void;
}>({ lang: 'en', setLang: () => {}, t: (k) => k, isOnline: true, toggleSimulateOffline: () => {} });

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('preferredLang') as Language) || 'en';
  });
  
  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('preferredLang', newLang);
  };
  
  const [isOnline, setIsOnline] = useState(navigator.onLine);
  const [simulateOffline, setSimulateOffline] = useState(false);

  useEffect(() => {
    const handleOnline = () => { if (!simulateOffline) setIsOnline(true); };
    const handleOffline = () => setIsOnline(false);
    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);
    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, [simulateOffline]);

  useEffect(() => {
    if (simulateOffline) {
      setIsOnline(false);
    } else {
      setIsOnline(navigator.onLine);
    }
  }, [simulateOffline]);

  const toggleSimulateOffline = () => setSimulateOffline(prev => !prev);

  const t = (key: keyof typeof translations.en) => (translations[lang] as any)[key] || translations.en[key];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isOnline, toggleSimulateOffline }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
